name: Fetch SG Price

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use Cache (Pip & Browsers)'
        type: boolean
        required: true
        default: true

jobs:
  fetch-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: ${{ github.event.inputs.use_cache == 'true' && 'pip' || '' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Playwright Browser Path
        id: playwright-path
        run: echo "path=$(python -c 'import Browser; print(Browser.__path__[0] + "/wrapper")')" >> $GITHUB_OUTPUT

      - name: Restore Playwright Browser Binaries
        if: github.event.inputs.use_cache == 'true'
        uses: actions/cache/restore@v4
        id: playwright-cache
        with:
          path: ${{ steps.playwright-path.outputs.path }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      - name: Initialize Browser
        if: steps.playwright-cache.outputs.cache-hit != 'true' || github.event.inputs.use_cache != 'true'
        run: |
          sudo python -m Browser.entry init --install-deps

      - name: Run Robot Test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/scripts/run_safegold_action.py

      - name: Upload Robot Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: robot-results/

      - name: Save Playwright Browser Binaries
        if: always() && github.event.inputs.use_cache == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.playwright-path.outputs.path }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}
